### ISSUE TITLE
Detail fork changes in ReadMe

### ISSUE THREAD

**Issue by TonyGravagno** [ctf0/PHP-Namespace-Resolver#12]
Ref: https://github.com/ctf0/PHP-Namespace-Resolver/issues/8#issuecomment-1374343520 by @ctf0  

> i wanted to rebase but its only prs changes which i've already did in the beginning + more, however I've made lots of changes that its not possible to compare anymore.

I completely understand.

Each individual using this fork will need to review each of your changes to decide if they will use your bundle, or continue with the upstream. "Apply Changes" and "Expose an API" are vague, requiring some research. It would be a shame for someone to pass by your FOSS contribution simply because it's not documented.

I suggest detailing your changes in the ReadMe so that users can make a quick decision to make use of your generous efforts. If you do have this info centralized, outside of comments in PRs or commits, please refer to that info in the ReadMe.

If you have merged changes from @MehediDracula and added more, he might want to rebase from your repo so that you guys can get back in sync.

Thanks

**Comment by ctf0** [comment]
ok i will try to update the readme, thanks agian for making this fork better.
