### ISSUE TITLE
New Update is causing PackageIntegrityCheckFailed

### ISSUE THREAD

**Issue by 247software-sanket-gandhi** [ctf0/PHP-Namespace-Resolver#13]
Hey @ctf0,

Seems like there was new update and it broke the extension. When I try to reinstall extension, it is showing me -

<img width="458" alt="image" src="https://user-images.githubusercontent.com/35518677/225814364-b2e70634-9ecf-4200-9da0-ffd4802300a3.png">

Logs -

```
2023-03-17 10:07:28.818 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed
```

Seems like the version present in VS Marketplace is different.

**Comment by ctf0** [comment]
yes am also having the same issue, am not sure what is the problem, its also happening with some other extensions not only mine.

for now u can download it and install it manually
