### ISSUE TITLE
Bad namespace resolution in a package, adds an unneeded slash

### ISSUE THREAD

**Issue by gruz** [ctf0/PHP-Namespace-Resolver#6]
How to reproduce
Clone this packages for example 
https://github.com/Jhnbrn90/BlogPackage

Open a file, it and try to generate a namespace

![Peek 2021-07-04 23-53](https://user-images.githubusercontent.com/422942/124399304-26d4b480-dd23-11eb-869f-ff0752b9ecff.gif)

**Comment by gruz** [comment]
Well....
Changing in `composer.json` `"JohnDoe\\BlogPackage\\": "src"` to `"JohnDoe\\BlogPackage\\": "src/"` solved the problem. I'm now not sure if it's a Namespace Resolver bug.

**Comment by alexkuc** [comment]
Hmmm, according to [composer docs](https://getcomposer.org/doc/04-schema.md#autoload), all of the folder path have a trailing `/`
