### ISSUE TITLE
Unused imports are no longer highlighted

### ISSUE THREAD

**Issue by alexkuc** [ctf0/PHP-Namespace-Resolver#7]
It seems that the option for showing unused imports is gone?:

![image](https://user-images.githubusercontent.com/3331946/135715037-c4627f3f-1e58-42c3-841a-813b0770ead1.png)

**Comment by ctf0** [comment]
sorry for the super late reply, yes removed as the highlight wasnt accurate most of the time, usually i use cs-fixer to get rid of them
