### ISSUE TITLE
Question: Have you bundled this fork?

### ISSUE THREAD

**Issue by TonyGravagno** [ctf0/PHP-Namespace-Resolver#8]
Thanks for forking and updating this extension. I'm trying to get by a persistent "Cannot read property '1' of null" error in the upstream version. I'd be happy to load and try this fork, and report issues here. But at this time I'm only a white-belt in "VSC-extension-Fu", and can't commit time to gain the necessary skill to bundle from source. (Yes, I have the doc, just no time with other commitments to main projects and FOSS.)

So, can you publish a VSIX of this version? I understand you haven't officially adopted the project, but as long as it's here it might as well get more visibility.

TY

(This kind of note would be better in a Discussions area, but at this time all we have are Issues.)

**Comment by ctf0** [comment]
sure np, here u go
[php-namespace-resolver-0.0.8.zip](https://github.com/ctf0/PHP-Namespace-Resolver/files/9825304/php-namespace-resolver-0.0.8.zip)

- just change the ext to `vsix`

**Comment by TonyGravagno** [comment]
I appreciate the bundle (ouch, just found it, thanks!) and will install as time permits. (Heavy into TS now, will get back to PHP soon.)

It seems @MehediDracula did make changes in 2022. It'll be difficult to diff out those changes with yours to identify what's missing or maybe re-fork for a hybrid (monster).

Do you plan to rebase or merge upstream PRs?

Any discussion with Mehedi about re-syncing?

Other thoughts?

Thanks!!

**Comment by ctf0** [comment]
i wanted to rebase but its only prs changes which i've already did in the beginning + more, however I've made lots of changes that its not possible to compare anymore.
